stages:
  - build
  - deploy

build:
  stage: build
  tags:
  - sc137394
  script:
  - chmod +x mvnw
  - ./mvnw clean install -P prod
  artifacts:
    expire_in: 24h
    paths:
      - backend/target/*.jar

deploy:
  stage: deploy
  tags:
  - sc137394
  script:
  - docker-compose up --build -d