build:
  tags:
  - sc137394
  script:
  - chmod +x mvnw
  - ./mvnw clean install -P prod
  artifacts:
    expire_in: 24h
    paths:
      - target/*.jar
      - Dockerfile
deploy:
  tags:
  - sc137394
  script:
  - docker-compose up -d