stages:
  - build
  - deploy

build:
  image: maven:3-jdk-8
  stage: build
  script:
  - mvn clean install -P prod
  artifacts:
    paths:
      - ma-backend/target/*.jar

deploy:
  stage: deploy
  tags:
  - sc137394
  script:
  - docker-compose up --build -d