version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
    - /home/gitlab-runner/mongodata:/data/db

  ma:
    build:
      context: .
    container_name: ma
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - mongodb