version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: unless-stopped

  ma:
    build:
      context: .
    container_name: ma
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mongodb